### ISSUE TITLE
Error: Type mismatch: inferred type is Boolean? but Boolean was expected

### ISSUE THREAD

**Issue by airstyl-tech** [ukkoon/multi_crop_picker#1]
Hi Please assist, I am getting the below error when I try to add this package

Stackoverflow question for more information: https://stackoverflow.com/questions/72370112/type-mismatch-inferred-type-is-boolean-but-boolean-was-expected?noredirect=1#comment127850433_72370112

: C:\Users\thzum\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\photo_manager-1.3.10\android\src\main\kotlin\top\kikt\imagescanner\core\PhotoManagerPlugin.kt: (101, 34): Type mismatch: inferred type is Boolean? but Boolean was expected
e: C:\Users\thzum\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\photo_manager-1.3.10\android\src\main\kotlin\top\kikt\imagescanner\core\PhotoManagerPlugin.kt: (101, 39): Type mismatch: inferred type is Boolean? but Boolean was expected
e: C:\Users\thzum\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\photo_manager-1.3.10\android\src\main\kotlin\top\kikt\imagescanner\core\PhotoManagerPlugin.kt: (128, 36): Type mismatch: inferred type is Boolean? but Boolean was expected
e: C:\Users\thzum\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\photo_manager-1.3.10\android\src\main\kotlin\top\kikt\imagescanner\core\PhotoManagerPlugin.kt: (128, 41): Type mismatch: inferred type is Boolean? but Boolean was expected

FAILURE: Build failed with an exception.
2

* What went wrong:
Execution failed for task ':photo_manager:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ukkoon** [comment]
sorry to late check,
do you solved it?
